// Code generated by protoc-gen-go. DO NOT EDIT.
// source: popcorn.proto

/*
Package popcorn is a generated protocol buffer package.

It is generated from these files:
	popcorn.proto

It has these top-level messages:
	StatsConfirmation
	Stats
	Package
	XUname
	ReportRequest
	StatsReport
	EmptyRequest
	EmptyResponse
*/
package popcorn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatsConfirmation struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StatsConfirmation) Reset()                    { *m = StatsConfirmation{} }
func (m *StatsConfirmation) String() string            { return proto.CompactTextString(m) }
func (*StatsConfirmation) ProtoMessage()               {}
func (*StatsConfirmation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Stats struct {
	HostID           *string    `protobuf:"bytes,1,req,name=HostID" json:"HostID,omitempty"`
	Pkgs             []*Package `protobuf:"bytes,2,rep,name=Pkgs" json:"Pkgs,omitempty"`
	XUname           *XUname    `protobuf:"bytes,3,opt,name=XUname" json:"XUname,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Stats) GetHostID() string {
	if m != nil && m.HostID != nil {
		return *m.HostID
	}
	return ""
}

func (m *Stats) GetPkgs() []*Package {
	if m != nil {
		return m.Pkgs
	}
	return nil
}

func (m *Stats) GetXUname() *XUname {
	if m != nil {
		return m.XUname
	}
	return nil
}

type Package struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Version          *string `protobuf:"bytes,2,req,name=Version" json:"Version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Package) Reset()                    { *m = Package{} }
func (m *Package) String() string            { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()               {}
func (*Package) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Package) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Package) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type XUname struct {
	OSName           *string `protobuf:"bytes,1,opt,name=OSName" json:"OSName,omitempty"`
	Kernel           *string `protobuf:"bytes,2,opt,name=Kernel" json:"Kernel,omitempty"`
	Mach             *string `protobuf:"bytes,3,opt,name=Mach" json:"Mach,omitempty"`
	CPUInfo          *string `protobuf:"bytes,4,opt,name=CPUInfo" json:"CPUInfo,omitempty"`
	UpdateStatus     *string `protobuf:"bytes,5,opt,name=UpdateStatus" json:"UpdateStatus,omitempty"`
	RepoStatus       *string `protobuf:"bytes,6,opt,name=RepoStatus" json:"RepoStatus,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *XUname) Reset()                    { *m = XUname{} }
func (m *XUname) String() string            { return proto.CompactTextString(m) }
func (*XUname) ProtoMessage()               {}
func (*XUname) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *XUname) GetOSName() string {
	if m != nil && m.OSName != nil {
		return *m.OSName
	}
	return ""
}

func (m *XUname) GetKernel() string {
	if m != nil && m.Kernel != nil {
		return *m.Kernel
	}
	return ""
}

func (m *XUname) GetMach() string {
	if m != nil && m.Mach != nil {
		return *m.Mach
	}
	return ""
}

func (m *XUname) GetCPUInfo() string {
	if m != nil && m.CPUInfo != nil {
		return *m.CPUInfo
	}
	return ""
}

func (m *XUname) GetUpdateStatus() string {
	if m != nil && m.UpdateStatus != nil {
		return *m.UpdateStatus
	}
	return ""
}

func (m *XUname) GetRepoStatus() string {
	if m != nil && m.RepoStatus != nil {
		return *m.RepoStatus
	}
	return ""
}

type ReportRequest struct {
	ResetRepo        *bool   `protobuf:"varint,1,opt,name=ResetRepo" json:"ResetRepo,omitempty"`
	ResetKey         *string `protobuf:"bytes,2,opt,name=ResetKey" json:"ResetKey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReportRequest) Reset()                    { *m = ReportRequest{} }
func (m *ReportRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()               {}
func (*ReportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReportRequest) GetResetRepo() bool {
	if m != nil && m.ResetRepo != nil {
		return *m.ResetRepo
	}
	return false
}

func (m *ReportRequest) GetResetKey() string {
	if m != nil && m.ResetKey != nil {
		return *m.ResetKey
	}
	return ""
}

type StatsReport struct {
	Report           []byte `protobuf:"bytes,1,req,name=Report" json:"Report,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StatsReport) Reset()                    { *m = StatsReport{} }
func (m *StatsReport) String() string            { return proto.CompactTextString(m) }
func (*StatsReport) ProtoMessage()               {}
func (*StatsReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StatsReport) GetReport() []byte {
	if m != nil {
		return m.Report
	}
	return nil
}

type EmptyRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EmptyRequest) Reset()                    { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string            { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()               {}
func (*EmptyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type EmptyResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EmptyResponse) Reset()                    { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()               {}
func (*EmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*StatsConfirmation)(nil), "StatsConfirmation")
	proto.RegisterType((*Stats)(nil), "Stats")
	proto.RegisterType((*Package)(nil), "Package")
	proto.RegisterType((*XUname)(nil), "XUname")
	proto.RegisterType((*ReportRequest)(nil), "ReportRequest")
	proto.RegisterType((*StatsReport)(nil), "StatsReport")
	proto.RegisterType((*EmptyRequest)(nil), "EmptyRequest")
	proto.RegisterType((*EmptyResponse)(nil), "EmptyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PopCorn service

type PopCornClient interface {
	Ping(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Update(ctx context.Context, in *Stats, opts ...grpc.CallOption) (*StatsConfirmation, error)
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*StatsReport, error)
}

type popCornClient struct {
	cc *grpc.ClientConn
}

func NewPopCornClient(cc *grpc.ClientConn) PopCornClient {
	return &popCornClient{cc}
}

func (c *popCornClient) Ping(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/PopCorn/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *popCornClient) Update(ctx context.Context, in *Stats, opts ...grpc.CallOption) (*StatsConfirmation, error) {
	out := new(StatsConfirmation)
	err := grpc.Invoke(ctx, "/PopCorn/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *popCornClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*StatsReport, error) {
	out := new(StatsReport)
	err := grpc.Invoke(ctx, "/PopCorn/Report", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PopCorn service

type PopCornServer interface {
	Ping(context.Context, *EmptyRequest) (*EmptyResponse, error)
	Update(context.Context, *Stats) (*StatsConfirmation, error)
	Report(context.Context, *ReportRequest) (*StatsReport, error)
}

func RegisterPopCornServer(s *grpc.Server, srv PopCornServer) {
	s.RegisterService(&_PopCorn_serviceDesc, srv)
}

func _PopCorn_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PopCornServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PopCorn/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PopCornServer).Ping(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PopCorn_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PopCornServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PopCorn/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PopCornServer).Update(ctx, req.(*Stats))
	}
	return interceptor(ctx, in, info, handler)
}

func _PopCorn_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PopCornServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PopCorn/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PopCornServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PopCorn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PopCorn",
	HandlerType: (*PopCornServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PopCorn_Ping_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PopCorn_Update_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _PopCorn_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "popcorn.proto",
}

func init() { proto.RegisterFile("popcorn.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0x87, 0x9b, 0x6c, 0x36, 0x69, 0xa7, 0x49, 0x11, 0x83, 0x84, 0xac, 0x68, 0x05, 0x95, 0x25,
	0x20, 0x27, 0x1f, 0x7a, 0xe1, 0x01, 0x0a, 0x12, 0xd5, 0x0a, 0x88, 0xbc, 0x2a, 0xe2, 0x84, 0x14,
	0x15, 0x6f, 0x89, 0x96, 0xda, 0x26, 0x76, 0x0f, 0xbd, 0xf3, 0x34, 0x3c, 0x25, 0xf2, 0x9f, 0x40,
	0xab, 0xbd, 0xf9, 0xfb, 0xea, 0x99, 0xf9, 0x8d, 0x1b, 0xa8, 0xb4, 0xd2, 0x3b, 0x35, 0x48, 0xa6,
	0x07, 0x65, 0x15, 0x7d, 0x06, 0x4f, 0xef, 0x6c, 0x67, 0xcd, 0x5a, 0xc9, 0xfb, 0x7e, 0x38, 0x74,
	0xb6, 0x57, 0x92, 0x7e, 0x83, 0x6b, 0x2f, 0xf1, 0x39, 0xe4, 0x1f, 0x94, 0xb1, 0x9b, 0x77, 0x24,
	0x59, 0xa6, 0xcd, 0x8c, 0x47, 0xc2, 0x1b, 0xc8, 0xda, 0x87, 0xbd, 0x21, 0xe9, 0xf2, 0xaa, 0x99,
	0xaf, 0xa6, 0xac, 0xed, 0x76, 0x0f, 0xdd, 0x5e, 0x70, 0x6f, 0xf1, 0x25, 0xe4, 0x5f, 0xb7, 0xb2,
	0x3b, 0x08, 0x72, 0xb5, 0x4c, 0x9a, 0xf9, 0xaa, 0x60, 0x01, 0x79, 0xd4, 0xf4, 0x2d, 0x14, 0xb1,
	0x02, 0x11, 0xb2, 0x4f, 0xee, 0x66, 0xe8, 0xef, 0xcf, 0x48, 0xa0, 0xf8, 0x22, 0x06, 0xd3, 0x2b,
	0x49, 0x52, 0xaf, 0x47, 0xa4, 0x7f, 0x92, 0xb1, 0xb5, 0x8b, 0xf6, 0xf9, 0x2e, 0x96, 0x26, 0x2e,
	0x5a, 0x20, 0xe7, 0x6f, 0xc5, 0x20, 0xc5, 0x4f, 0x92, 0x06, 0x1f, 0xc8, 0x0d, 0xfa, 0xd8, 0xed,
	0x7e, 0xf8, 0x48, 0x33, 0xee, 0xcf, 0x6e, 0xd0, 0xba, 0xdd, 0x6e, 0xe4, 0xbd, 0x22, 0x99, 0xd7,
	0x23, 0x22, 0x85, 0x72, 0xab, 0xbf, 0x77, 0x56, 0xb8, 0x77, 0x38, 0x1a, 0x72, 0xed, 0x7f, 0xbe,
	0x70, 0xf8, 0x02, 0x80, 0x0b, 0xad, 0xe2, 0x8d, 0xdc, 0xdf, 0x38, 0x33, 0x74, 0x03, 0x95, 0xa3,
	0xc1, 0x72, 0xf1, 0xeb, 0x28, 0x8c, 0xc5, 0x1b, 0x98, 0x71, 0x61, 0x84, 0x75, 0xd6, 0xa7, 0x9e,
	0xf2, 0xff, 0x02, 0x6b, 0x98, 0x7a, 0xb8, 0x15, 0xa7, 0x18, 0xfd, 0x1f, 0xd3, 0x57, 0x30, 0xf7,
	0x7f, 0x48, 0xe8, 0xe7, 0x76, 0x0c, 0x27, 0xff, 0x6c, 0x25, 0x8f, 0x44, 0x17, 0x50, 0xbe, 0x3f,
	0x68, 0x7b, 0x8a, 0x03, 0xe9, 0x13, 0xa8, 0x22, 0x1b, 0xad, 0xa4, 0x11, 0xab, 0xdf, 0x09, 0x14,
	0xad, 0xd2, 0x6b, 0x35, 0x48, 0x7c, 0x03, 0x59, 0xdb, 0xcb, 0x3d, 0x56, 0xec, 0xbc, 0xa6, 0x5e,
	0xb0, 0x8b, 0x12, 0x3a, 0xc1, 0xd7, 0x90, 0x87, 0xbd, 0x31, 0x67, 0x3e, 0x45, 0x8d, 0xec, 0xf1,
	0x37, 0x33, 0xc1, 0x66, 0x4c, 0x85, 0x0b, 0x76, 0xb1, 0x78, 0x5d, 0xb2, 0xb3, 0xf4, 0x74, 0xf2,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xa6, 0x3f, 0xdc, 0x84, 0x02, 0x00, 0x00,
}
