FROM golang:1.15-alpine as build
WORKDIR /popcorn/
COPY . .
RUN go mod vendor && \
        CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o /popcornd ./cmd/popcornd && \
        apk add upx binutils && \
        strip /popcornd && \
        upx /popcornd && \
        ls -alh /popcornd

FROM scratch
LABEL org.opencontainers.image.source https://github.com/the-maldridge/popcorn
ENTRYPOINT ["/popcornd"]
COPY --from=build /popcornd /popcornd
