FROM golang:1.15-alpine as build
WORKDIR /popcorn/
COPY . .
RUN go mod vendor && \
        CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o /pgrpcgw ./cmd/pgrpcgw && \
        apk add upx binutils && \
        strip /pgrpcgw && \
        upx /pgrpcgw && \
        ls -alh /pgrpcgw

FROM scratch
LABEL org.opencontainers.image.source https://github.com/the-maldridge/popcorn
ENTRYPOINT ["/pgrpcgw"]
COPY --from=build /pgprcgw /pgprcgw
